# Docker Compose 
# Para compor as imagens docker 
version: "3.9"

# Criar network para conectar os containers
# Bridge: network padrão para conexão entre containers
# Host: minha network
networks:
  rentx-network:
    name: rentx-network
    driver: bridge

services:
  rentx-database:
    image: postgres
    container_name: rentx-database
    restart: always
    networks:
      - "rentx-network"
    ports: 
      - 5432:5432
    volumes:
      - ./database/postgres:/database/postgres
    environment:
      - POSTGRES_DB=rentx
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      
  rentx-backend:
    build: .
    restart: always
    container_name: rentx-backend
    networks:
      - "rentx-network"
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - ./src:/app/backend/src
    links: 
      - rentx-database
    depends_on:
      - rentx-database