version: "3.9"

services:
  prisma-database:
    image: postgres
    container_name: prisma-database
    restart: always
    ports: 
      - 65432:5432
    volumes:
      - ./database/postgres:/database/postgres
    environment:
      - POSTGRES_DB=prisma
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin